[package]
name = "zirael_core"
edition.workspace = true
license.workspace = true
version.workspace = true
repository.workspace = true

[dependencies]
parking_lot = { workspace = true }
ariadne = { workspace = true }
dashmap = { workspace = true }
id-arena = { workspace = true }

[lints]
workspace = true
