[package]
name = "zirael_core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zirael Core"

[dependencies]
anyhow = { workspace = true }
colored = { workspace = true }
fs-err = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
zirael_parser = { workspace = true }
zirael_utils = { workspace = true }

[lints]
workspace = true
