[package]
name = "zirael_utils"
edition.workspace = true
license.workspace = true
version.workspace = true
repository.workspace = true
description = "Zirael Utils"

[dependencies]
anstyle = { workspace = true }
clap = { workspace = true }
parking_lot = { workspace = true }
id-arena = { workspace = true }
once_cell = { workspace = true }
lasso = { workspace = true }
ariadne = { workspace = true }

[lints]
workspace = true
