[package]
name = "zirael_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ariadne = { workspace = true }
colored = { workspace = true }
logos = { workspace = true }
zirael_utils = { workspace = true }
fs-err = { workspace = true }

[lints]
workspace = true
